### ISSUE TITLE
Als Linux-gebruiker wil ik (ook) graag kunnen testen

### ISSUE THREAD

**Issue by adgerrits** [VNG-Realisatie/Haal-Centraal-BRK-event-sourcing#35]
Poging gedaan maar krijg 'de twee kadastrale containers' niet gestart vanwege (lijkt het) probleem met benodigd server/developer certificaat. Nog even gegoogled naar 'Linux aspnetcore certificate' maar dat is (voor mij) een brug te ver'.

**Comment by CathyDingemanse** [comment]
@MelvLee zou jij willen kijken of je @adgerrits hiermee kunt helpen? Thnx!

**Comment by MelvLee** [comment]
@adgerrits, met de fix die is ingecheckt, moet het developer certificaat probleem zijn opgelost
